config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|es/ do

  	root 'main#index'

  	get 'main/index'
  	get 'main/services'
  	get 'main/developments'
  	get 'main/capabilities'
    get 'main/contact'
  	get 'main/aboutUs'
  	# get 'main/galeon'
  end
  

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/translation.rb
class Translation < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	around_action :switch_locale
	 
	def switch_locale(&action)
	  @locale = params[:locale] || I18n.default_locale
	  I18n.with_locale(@locale, &action)
	end


	def default_url_options
	  { locale: I18n.locale }
	end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    # @locale = "es"
  	@statusIndex = "active"
  	@statusServices = ""
    @statusCapabilities = ""
    @statusDevelopments = ""
  	@statusAboutUs = ""
    @statusContact = ""
    @statusGaleon = ""
  end

  def services
    @statusIndex = ""
    @statusServices = "active"
    @statusCapabilities = ""
    @statusDevelopments = ""
    @statusAboutUs = ""
    @statusContact = ""
    @statusGaleon = ""
  end

  def capabilities
  	@statusIndex = ""
  	@statusServices = ""
    @statusCapabilities = "active"
  	@statusDevelopments = ""
    @statusAboutUs = ""
    @statusContact = ""
    @statusGaleon = ""
  end

  def developments
    @statusIndex = ""
    @statusServices = ""
    @statusCapabilities = ""
    @statusDevelopments = "active"
    @statusAboutUs = ""
    @statusContact = ""
    @statusGaleon = ""
  end

  def aboutUs
  	@statusIndex = ""
  	@statusServices = ""
    @statusCapabilities = ""
  	@statusDevelopments = ""
    @statusAboutUs = "active"
    @statusContact = ""
    @statusGaleon = ""
  end

  def contact
    @statusIndex = ""
    @statusServices = ""
    @statusCapabilities = ""
    @statusDevelopments = ""
    @statusAboutUs = ""
    @statusContact = "active"
    @statusGaleon = ""
  end

  def galeon
    @statusIndex = ""
    @statusServices = ""
    @statusCapabilities = ""
    @statusDevelopments = ""
    @statusAboutUs = ""
    @statusContact = ""
    @statusGaleon = "active"
  end
  
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_action :set_translation, only: [:show, :edit, :update, :destroy]
  layout 'translations_controller'
  # GET /translations
  # GET /translations.json
  def index
    @translations = Translation.all
  end

  # GET /translations/1
  # GET /translations/1.json
  def show
  end

  # GET /translations/new
  def new
    @translation = Translation.new
  end

  # GET /translations/1/edit
  def edit
  end

  # POST /translations
  # POST /translations.json
  def create
    @translation = Translation.new(translation_params)

    respond_to do |format|
      if @translation.save
        format.html { redirect_to @translation, notice: 'Translation was successfully created.' }
        format.json { render :show, status: :created, location: @translation }
      else
        format.html { render :new }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /translations/1
  # PATCH/PUT /translations/1.json
  def update
    respond_to do |format|
      if @translation.update(translation_params)
        format.html { redirect_to @translation, notice: 'Translation was successfully updated.' }
        format.json { render :show, status: :ok, location: @translation }
      else
        format.html { render :edit }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translations/1
  # DELETE /translations/1.json
  def destroy
    @translation.destroy
    respond_to do |format|
      format.html { redirect_to translations_url, notice: 'Translation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_translation
      @translation = Translation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def translation_params
      params.require(:translation).permit(:locale, :key, :value, :interpolations, :is_proc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeepCo S.A.S | Tecnología Subacuática | ROV | Colombia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- <meta name="description" content="Deepco is a Colombian company focused in the utilization of underwater technology to conserve the marine enviroment"> -->
    <meta name="description" content="DeepCo es una compañía Colombiana enfocada en desarrollo de tecnología subacuática para conservar el entorno marino. DeepCo S.A.S">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Lato' rel="stylesheet">
    <!-- <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet"> -->
  </head>

  <body>

    <nav class="navbar sticky-top navbar-expand-lg navbar-expand-md navbar-light bg-white">
      <div class="navbar-brand" id="logo-img">
        <%=link_to image_tag("deepco.png", alt: "deepco", class:"img-fluid"), main_index_path if @locale != "es" && @locale != "en" %>
       <%=link_to image_tag("deepco.png", alt: "deepco", class:"img-fluid"), main_index_path if @locale == "es" %>
       <%=link_to image_tag("deepco_en.png", alt: "deepco", class:"img-fluid"), main_index_path if @locale == "en" %> 
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item <%= @statusIndex %> text-center">
            <%= link_to(main_index_path, class:"nav-link") do %>
              <%= t :index %>
            <% end %>            
          </li>
          <ul class="nav-item <%= @statusServices%> <%= @statusDevelopments%> dropdown text-center">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <%= t :services %> </a>
            <div id="navbarDropdown" class="dropdown-menu border-0 text-center" aria-labelledby="navbarDropdown">
              <div><%= link_to (t :services1), main_services_path %></div>
              <div><%= link_to (t :developments), main_developments_path %></div>
            </div>  
          </ul>
          <li class="nav-item <%= @statusCapabilities %> text-center">
            <%= link_to(main_capabilities_path, class:"nav-link") do %>
              <%= t :capabilities %>
            <% end %>   
          </li>
          <li class="nav-item <%= @statusAboutUs %> text-center">
            <%= link_to(main_aboutUs_path, class:"nav-link") do %>
              <%= t :aboutUs %>
            <% end %>  
          </li>
          <li class="nav-item <%= @statusContact %> text-center">
            <%= link_to(main_contact_path, class:"nav-link") do %>
              <%= t :contact %>
            <% end %>  
          </li>
          <!-- <ul class="nav-item dropdown text-center">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <%= t :language %> </a>
            <div id="navbarDropdown" class="dropdown-menu border-0 text-center" aria-labelledby="navbarDropdown">
              <div><%= link_to (t :language1), locale: :en %></div> 
              <div><%= link_to (t :language2), locale: :es %></div>
            </div>  
          </ul> -->
        </ul>
      </div>
    </nav>

    <%= yield %>

    <!-- Footer -->
    <footer class="page-footer font-small stylish-color-dark pt-4 marginAboutUs">

      <!-- Footer Links -->
      <div class="container-fluid text-center text-md-left">

        <!-- Grid row -->
        <div class="row">

          <!-- Grid column -->
          <div class="col-md-6 mt-md-0 mt-3">

            <!-- Content -->
            <h5 class="text-uppercase text-center"><%= t :findUsTitle %></h5>
            <div class="text-center">
              <a href= "https://www.facebook.com/DeepColombia/" class="fa fa-facebook" target="_blank" aria-hidden="true"></a>
              <a href= "https://www.linkedin.com/company/deepco-sas/" class="fa fa-linkedin" target="_blank" aria-hidden="true"></a>
            </div>          

          </div>
          <!-- Grid column -->

          <hr class="clearfix w-100 d-md-none pb-3">

          <!-- Grid column -->
          <div class="col-md-3 mb-md-0 mb-3 col-sm-12 col-xsm-6 border-left">

              <!-- Links -->
              <!-- <h5 class="text-uppercase">Links</h5> -->

              <ul class="list-unstyled">
                <li>
                  <%= link_to(main_index_path) do %>
                    <%= t :index %>
                  <% end %>             
                </li>
                <li>
                  <%= link_to(main_services_path) do %>
                    <%= t :services1 %>
                  <% end %>
                </li>
                <li>
                  <%= link_to(main_services_path) do %>
                    <%= t :developments %>
                  <% end %>
                </li>
                <li>
                  <%= link_to(main_capabilities_path) do %>
                    <%= t :capabilities %>
                  <% end %>
                </li>
                <li>
                  <%= link_to(main_aboutUs_path) do %>
                    <%= t :aboutUs %>
                  <% end %>
                </li>
                <li>
                  <%= link_to(main_contact_path) do %>
                    <%= t :contact %>
                  <% end %>
                </li>
              </ul>

          </div>
            <!-- Grid column -->
        </div>

        <div class="row">
          <div class="col-md-6 mt-md-0 mt-3 text-center"> 
            <h5 class="text-uppercase"><%= t :mailUsTitle %></h5>             
            <!-- <a href="+57" class="mailto fa fa-phone text-center" target="_blank"> +57 3007921144</a>          -->
            <a href="mailto:contacto@deepco.com.co" class="fa fa-envelope text-center" target="_blank"> contacto@deepco.com.co</a>
                        
          </div> 
        </div>
        <!-- Grid row -->

      </div>
      <!-- Footer Links -->

      <!-- Copyright -->
      <div class="footer-copyright text-center py-3">2018 © Copyright
        <a>DeepCo.</a>
        <a><%= t :copyright %></a>
      </div>
      <!-- Copyright -->

    </footer>
    <!-- Footer -->

  </body>
</html>

app/views/layouts/translations_controller.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<!-- <meta name="description" content="Deepco is a Colombian company focused in the utilization of underwater technology to conserve the marine enviroment"> -->
    <!-- <meta name="description" content="DeepCo es una compañía Colombiana enfocada en desarrollo de tecnología subacuática para conservar el entorno marino. DeepCo S.A.S"> -->
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %> -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
    <!-- <link href='https://fonts.googleapis.com/css?family=Lato' rel="stylesheet"> -->
    <!-- <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet"> -->
  </head>
  <body>
    <ul>
      <li><%= link_to (t :language1), locale: :en %></li>
      <li><%= link_to (t :language2), locale: :es %></li>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/main/aboutUs.html.erb
	<div id="imageAboutUs" class="container margin">
      <%= image_tag("aboutUs/deepco_1", alt: "deepco", class:"img-fluid") if @locale == "es" %>
      <%= image_tag("aboutUs/deepco_2", alt: "deepco", class:"img-fluid") if @locale == "en" %>
      
  </div>
    
    <div class="container margin3">
      <h1 class="deepColor text-center"><%= t :misionTitle %></h1>
      <p class="textSection text-justify"><%= t :misionText %></p>
    </div>

    <div class="container margin3">
      <h1 class="deepColor text-center"><%= t :visionTitle %></h1>
      <p class="textSection text-justify"><%= t :visionText %></p>
    </div>

    <div class="container margin3">
      <h1 class="deepColor text-center"><%= t :valueTitle %></h1>
      <p class="textSection text-justify"><%= t :valueText %></p>
    </div>

    <!-- DeepCo TEAM -->
    <h2 class="margin3 text-center deepColor"><%= t :ourTeamTitle %></h2>
    <div class="container text-center text-md-left margin">

      <div class="row">

        <div class="col-md-2">
          <%= link_to(image_tag("aboutUs/us/deepco_SAS.jpg", :alt => "deepco", class:"img-fluid center deepPhotos"), "https://www.linkedin.com/in/sergio-suarez-809771a8", target: "_blank") %>
        </div>

        <div class="col-md-4">
          <h4><%= t :member1Name %></h4>
          <h5><%= t :member1Qualification %></h5>
          <p class="justify"><%= t :member1Description %></p>
          <p class="justify"><%= t :member1Email %></p>
        </div>

        <div class="col-md-2">
          <%= link_to(image_tag("aboutUs/us/deepco_CVC.jpg", alt: "deepco", class:"img-fluid center deepPhotos"), "https://www.linkedin.com/in/cindy-carmona-cadavid-41880b3b/", target: "_blank") %> 
        </div>

        <div class="col-md-4">
          <h4><%= t :member5Name %></h4>
          <h5><%= t :member5Qualification %></h5>
          <p class="justify"><%= t :member5Description %></p>
          <p class="justify"><%= t :member5Email %></p>
        </div>

        <div class="col-md-2 marginAboutUs">
          <%= link_to(image_tag("aboutUs/us/deepco_CDM.jpg", alt: "deepco", class:"img-fluid center deepPhotos"), "https://www.linkedin.com/in/cristian-david-mart%C3%ADnez-posada-43024056/", target: "_blank") %> 
        </div>

        <div class="col-md-4 marginAboutUs">
          <h4><%= t :member8Name %></h4>
          <h5><%= t :member8Qualification %></h5>
          <p class="justify"><%= t :member8Description %></p>
          <p class="justify"><%= t :member8Email %></p>
        </div>

      </div>
    </div>


    <!-- Asesores -->
    <h2 class="margin text-center deepColor"><%= t :advisorTitle %></h2>
    <div class="container text-center text-md-left margin">

      <div class="row">

        <div class="col-md-2">
          <%= link_to(image_tag("aboutUs/us/deepco_DCH.jpg", alt: "deepco", class:"img-fluid center deepPhotos"), "https://www.linkedin.com/in/diana-hern%C3%A1ndez-7771415b/", target: "_blank") %>
        </div>

        <div class="col-md-4">
          <h4><%= t :member2Name %></h4>
          <h5><%= t :member2Qualification %></h5>
          <p class="justify"><%= t :member2Description %></p>
        </div>

        <!-- <div class="col-md-2">
          <%=image_tag("aboutUs/us/deepco_ABG.jpg", alt: "deepco", class:"img-fluid center deepPhotos")%>
        </div>

        <div class="col-md-4">
          <h4><%= t :member6Name %></h4>
          <h5><%= t :member6Qualification %></h5>
          <p class="justify"><%= t :member6Description %></p>
        </div> -->

        <div class="col-md-2">
          <%= link_to(image_tag("aboutUs/us/deepco_EPV.jpg", :alt => "deepco", class:"img-fluid center deepPhotos"), "https://www.linkedin.com/in/estebanpalaciove/", target: "_blank") %>
        </div>

        <div class="col-md-4">
          <h4><%= t :member3Name %></h4>
          <h5><%= t :member3Qualification %></h5>
          <p class="justify"><%= t :member3Description %></p>
        </div>

        <div class="col-md-2">
          <%= link_to(image_tag("aboutUs/us/deepco_YV.jpg", alt: "deepco", class:"img-fluid center deepPhotos"), "https://www.linkedin.com/in/yesid-valencia-soto-33589759/", target: "_blank") %>
        </div>

        <div class="col-md-4">
          <h4><%= t :member7Name %></h4>
          <h5><%= t :member7Qualification %></h5>
          <p class="justify"><%= t :member7Description %></p>
        </div>

        <div class="col-md-2">
          <%= link_to(image_tag("aboutUs/us/deepco_LMA.jpg", alt: "deepco", class:"img-fluid center deepPhotos"), "https://www.linkedin.com/in/luis-miguel-a-923a44142/", target: "_blank") %>
        </div>

        <div class="col-md-4">
          <h4><%= t :member4Name %></h4>
          <h5><%= t :member4Qualification %></h5>
          <p class="justify"><%= t :member4Description %></p>
        </div>

      </div>
    </div>

app/views/main/capabilities.html.erb
<div class="container margin3 justify">  
  <h1 class="deepColor"><%= t :capabilities %></h1>
</div>

<div class="container margin3 justify">
  <div class="row">
    <div class="col-lg-12 col-sm-12 col-md-12 margin1 justify">
      <h2 class="deepColor"><%= t :experienceTitle %></h2>

        <div>
          <div class="container margin3 bordeDeepco text-center text-md-left">
            <div class="row">
              <div class="col-md-2 col-sm-12 col-12 my-auto iconsService mx-auto marginForCellphone">
                <%=image_tag("logos/deepco_upb2", alt: "deepco", class:"d-block w-100 mx-auto")%>
              </div>
              <div class="col-md-2 col-sm-12 col-12 my-auto iconsService mx-auto marginForCellphone">
                <%=image_tag("logos/deepco_ecopetrol", alt: "deepco", class:"d-block w-100 mx-auto")%>
              </div>
              <div class="col-md-8 col-sm-12 col-12 my-auto justify">
                <div><%= t :experienceText11 %></div>
              </div>
            </div>
          </div>
        </div>

        <div>
          <div class="container margin3 bordeDeepco text-center text-md-left">
            <div class="row">
              <div class="col-md-4 col-sm-12 col-12 my-auto iconsService mx-auto marginForCellphone">
                <%=image_tag("logos/deepco_udea", alt: "deepco", class:"d-block w-100 mx-auto")%>
              </div>
              <div class="col-md-8 col-sm-12 col-12 my-auto justify">
                <div><%= t :experienceText12 %></div>
              </div>
            </div>
          </div>
        </div>

        <div>
          <div class="container margin3 bordeDeepco text-center text-md-left">
            <div class="row">
              <div class="col-md-2 col-sm-12 col-12 my-auto iconsService mx-auto marginForCellphone">
                <%=image_tag("logos/deepco_418", alt: "deepco", class:"d-block w-100 mx-auto")%>
              </div>
              <div class="col-md-2 col-sm-12 col-12 my-auto iconsService mx-auto marginForCellphone">
                <%=image_tag("logos/deepco_felipeDiving", alt: "deepco", class:"d-block w-100 mx-auto")%>
              </div>
              <div class="col-md-8 col-sm-12 col-12 my-auto justify">
                <div><%= t :experienceText13 %></div>
              </div>
            </div>
          </div>
        </div>

    </div>
  </div>
</div>

<div class="container margin3 justify">
  <div class="row">
    <div class="col-lg-12 col-sm-12 col-md-12 justify">
      <h2 class="deepColor"><%= t :experienceTitle2 %></h2>

        <div>
          <div class="container margin3 bordeDeepco text-center text-md-left">
            <div class="row">
              <div class="col-md-4 col-sm-12 col-12 my-auto iconsService mx-auto marginForCellphone">
                <%=image_tag("logos/deepco_coralesDePaz", alt: "deepco", class:"d-block w-100 mx-auto")%>
              </div>
              <div class="col-md-8 col-sm-12 col-12 my-auto justify">
                <div><%= t :experienceText21 %></div>
              </div>
            </div>
          </div>
        </div>

        <div>
          <div class="container margin3 bordeDeepco text-center text-md-left">
            <div class="row">
              <div class="col-md-4 col-sm-12 col-12 my-auto iconsService mx-auto marginForCellphone">
                <%=image_tag("logos/deepco_dita", alt: "deepco", class:"d-block w-100 mx-auto")%>
              </div>
              <div class="col-md-8 col-sm-12 col-12 my-auto justify">
                <div><%= t :experienceText22 %></div>
              </div>
            </div>
          </div>
        </div>

        <div>
          <div class="container margin3 bordeDeepco text-center text-md-left">
            <div class="row">
              <div class="col-md-4 col-sm-12 col-12 my-auto iconsService mx-auto marginForCellphone">
                <%=image_tag("logos/deepco_gotta", alt: "deepco", class:"d-block w-100 mx-auto")%>
              </div>
              <div class="col-md-8 col-sm-12 col-12 my-auto justify">
                <div><%= t :experienceText23 %></div>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/main/contact.html.erb
<div class="container margin justify">  
  <h1 class="deepColor"><%= t :contactTitle %></h1>
</div>

<div class="container containerContacto margin2">
  <h2 class="text-center"><%= t :contactText1 %></h2>
  <h3 class="margin1 text-center"><%= t :deepcoMail %></h3>
  <h2 class="text-center margin"><%= t :contactText2 %></h2>
  <h3 class="margin1 text-center"><%= t :deepcoPhone %></h3>
  <!-- <h3 class="">sergio.suarez@deepco.com.co</h3>
  <h3 class="">cindy.carmona@deepco.com.co</h3> -->
</div>

app/views/main/index.html.erb
    <div id="demo" class="carousel slide" data-ride="carousel">

      <!-- Indicators -->
      <ul class="carousel-indicators">
        <li data-target="#demo" data-slide-to="0" class="active"></li>
        <li data-target="#demo" data-slide-to="1"></li>
        <li data-target="#demo" data-slide-to="2"></li>
      </ul>

      <!-- The slideshow -->
      <div id="videoHP" class="carousel-inner">
        <div class="carousel-item active">
          <video class="w-100" autoplay muted loop>
            <source src="/videos/deepco_2.mp4" type="video/mp4">
            Your browser does not support the video tag.
          </video>
          <div class="carousel-caption1 d-none d-md-block">
            <h1 class="deepColor justify"><%= t :slide1title %></h1>
            <div class="slideShowText1 justify"><%= t :slide1text %></div>
          </div>
          <!-- <div class="carousel-caption d-none d-md-block">
            <h1 class="deepColor">Pionero500</h1>
            <div class="slideShowText1">Puesta a punto del vehiculo operado remotamente desarrollado por la Universidad Pontificia Bolivariana</div>
          </div> -->
        </div>
        <div class="carousel-item">
          <%=image_tag("homePage/deepco_2.jpg", alt: "deepco", class:"d-block w-100")%>
          <div class="carousel-caption2 d-none d-md-block">
            <h1 class="deepColor justify"><%= t :slide2title %></h1>
            <div class="slideShowText2 justify"><%= t :slide2text %></div>
          </div>
        </div>
        <div class="carousel-item">
          <%=image_tag("homePage/deepco_3.jpg", alt: "deepco", class:"d-block w-100")%>
          <div class="carousel-caption3 d-none d-md-block">
            <h1 class="deepColor justify"><%= t :slide3title %></h1>
            <div class="slideShowText3 justify"><%= t :slide3text %></div>
          </div>
        </div>
      </div>

      <!-- Left and right controls -->
      <a class="carousel-control-prev" href="#demo" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
      </a>
      <a class="carousel-control-next" href="#demo" data-slide="next">
        <span class="carousel-control-next-icon"></span>
      </a>

    </div>

    <div class="container margin text-center">
      <h1 class="deepColor"><%= t :whatDeepcoTitle %></h1>
      <p class="textSection"><%= t :whatDeepcoText %></p>
    </div>

    <div class="parallax1 margin"></div>

    <div class="container margin text-center">
      <h1 class="deepColor"><%= t :whatDeepcoDoesTitle %></h1>
      <p class="textSection"><%= t :whatDeepcoDoesText %></p>
    </div>

    <div class="parallax2 margin"></div>

    <div class="container margin text-center">
      <h1 class="deepColor"><%= t :howDeepcoDoesTitle %></h1>
      <p class="textSection"><%= t :howDeepcoDoesText %></p>
    </div>

    <div id="servicios" class="container margin">
      <div class="row">
        <div class="col-xl-4 col-lg-4 col-md-4 col-sm">
          <div class="container overflow-hidden">
            <div>
            	<%=link_to image_tag("servicios/deepco_1.jpg", alt: "deepco", class:"hover-shadow img-fluid img-thumbnail"), main_capabilities_path %>
              <div class="centered"><p><%= t :capabilities1 %></p></div>
            </div>
          </div>
        </div>
        <div class="col-xl-4 col-lg-4 col-md-4 col-sm">
          <div class="container overflow-hidden">
            <div>
              <%=link_to image_tag("servicios/deepco_2.jpg", alt: "deepco", class:"hover-shadow img-fluid img-thumbnail"), main_capabilities_path%>
              <div class="centered"><p><%= t :capabilities2 %></p></div>
            </div>
          </div>
        </div>
        <div class="col-xl-4 col-lg-4 col-md-4 col-sm">
          <div class="container overflow-hidden">
            <div>
              <%=link_to image_tag("servicios/deepco_3.jpg", alt: "deepco", class:"hover-shadow img-fluid img-thumbnail"), main_capabilities_path%>
              <div class="centered"><p><%= t :capabilities3 %></p></div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- <h2 class="margin text-center">Apoyan</h2> -->
    <div class="row">
      <div class="col-12 text-center marginAboutUs">
        <h3><%= t :supportedBy %></h3>
      </div>
      <div class="col-6 text-center marginAboutUs mx-auto">
        <div>
          <%=image_tag("logos/deepco_upb-cde", alt: "deepco", class:"img-fluid")%>
        </div>
      </div>
      <!-- <div class="col-6 text-center marginAboutUs">
        <div class="">
          <%=image_tag("logos/deepco_upb", alt: "deepco", class:"img-fluid w-25")%>
        </div>
      </div>
      <div class="col-6 text-center marginAboutUs">
        <div class="">
          <%=image_tag("logos/deepco_cde", alt: "deepco", class:"img-fluid w-25")%>
        </div>
      </div> -->
    </div>
  
  

app/views/translations/edit.html.erb
<h1>Editing Translation</h1>

<%= render 'form', translation: @translation %>

<%= link_to 'Show', @translation %> |
<%= link_to 'Back', translations_path %>

app/views/translations/new.html.erb
<h1>New Translation</h1>

<%= render 'form', translation: @translation %>

<%= link_to 'Back', translations_path %>